// =====================================================================
// gen_e2_coverage_manifest.mjs — REF-1.1 E2.0: GENERATE the source-site → row
// coverage manifest (Aster E2.0 re-review 2795636a cond.3 / correction a767b880).
//
// Aster requires a GENERATED ARTIFACT that maps each IMMUTABLE source-site identity
// to its intended boundary row, so exact source-site-to-intended-row SET EQUALITY
// can be asserted — the distinct (boundary, wire, transportKind) triples are only
// an injection implementation-check, not the mapping itself.
//
// The IMMUTABLE identity is (source-file basename ‖ wire ‖ transportKind) — stable
// across line-number churn, unlike file:line. Each is resolved to the registry row
// (row.type) its intended boundary declares for that (wire, transportKind).
//
// Emits test/REF-1.1-E2-coverage-manifest.json. The fence (fence_e2_coverage.mjs)
// re-runs this in memory and asserts the committed artifact is byte-identical, so
// the artifact can never drift from the registries.
//
//   node test/gen_e2_coverage_manifest.mjs           # print + verify in sync
//   node test/gen_e2_coverage_manifest.mjs --write    # (re)write the artifact
// =====================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { rowDefs as r1, frameWiring as f1 } from '../src/pubsub/boundary1Registry.js';
import { rowDefs as r2, frameWiring as f2 } from '../src/transport/boundary2Registry.js';
import { rowDefs as r3, frameWiring as f3 } from '../src/transport/boundary3Registry.js';
import { rowDefs as r4, frameWiring as f4 } from '../src/transport/boundary4Registry.js';
import { rowDefs as r5, frameWiring as f5 } from '../src/dht/boundary5Registry.js';
import { rowDefs as r6, frameWiring as f6 } from '../src/dht/boundary6Registry.js';

const E0 = fileURLToPath(new URL('./REF-1.1-E0-manifest.json', import.meta.url));
const OUT = fileURLToPath(new URL('./REF-1.1-E2-coverage-manifest.json', import.meta.url));
const TK = { onRequest: 'request', onNotification: 'notification', onRoutedMessage: 'routed', 'on(T.*)': 'routed' };

// intended E2.0 boundary from the E0 manifest boundary label; `B2/B3` (the two
// `hello` sites) split by the manifest receiver tag (bridge → B2, webrtc → B3).
function intendedBoundary(row) {
  const b = row.boundary;
  if (b === 'B1' || b === 'B2' || b === 'B3') return b;
  if (b === 'dht:transport') return 'B5';
  if (b === 'direct') return 'B6';
  if (b === 'B2/B3') return row.receiver === 'bridge' ? 'B2' : row.receiver === 'webrtc' ? 'B3' : null;
  return null;
}

// The registries, keyed by intended-boundary label. Value maps (wire, transportKind)
// -> row.type by scanning the frameWiring (bare-keyed B1–B5, composite-keyed B6);
// every wiring value carries transportKind (except B4, which owns no target).
const REG = { B1: f1(r1()), B2: f2(r2()), B3: f3(r3()), B4: f4(r4()), B5: f5(r5()), B6: f6(r6()) };
function resolveRowType(boundary, wire, tk) {
  for (const [key, v] of REG[boundary]) if ((v.wire ?? key) === wire && v.transportKind === tk) return v.type;
  return null;
}

export function generate() {
  const manifest = JSON.parse(readFileSync(E0, 'utf8'));
  const targets = manifest.rows.filter((r) => r.classification === 'migration-target');
  const sites = targets.map((row) => {
    const wire = row.wire;
    const transportKind = TK[row.callee] ?? null;
    const boundary = intendedBoundary(row);
    const receiver = row.receiver ?? '';
    // Immutable source-site identity: (file ‖ wire ‖ transportKind ‖ receiver). The
    // receiver is the intrinsic object the handler binds to (NOT the intended
    // boundary), and it is the only thing that distinguishes the two same-file
    // `hello` sites (bridge → B2, webrtc → B3). Stable across line-number churn.
    const identity = `${row.file}|${wire}|${transportKind}|${receiver}`;
    const rowType = (boundary && transportKind) ? resolveRowType(boundary, wire, transportKind) : null;
    return { identity, site: `${row.file}:${row.line}`, receiver, wire, transportKind, boundary, rowType };
  }).sort((a, b) => a.identity < b.identity ? -1 : a.identity > b.identity ? 1 : 0);
  return {
    _comment: 'GENERATED by gen_e2_coverage_manifest.mjs from REF-1.1-E0-manifest.json + the B1–B6 registries. Do not hand-edit; the fence drift-checks it. Each entry maps an immutable source-site identity (basename|wire|transportKind) to the boundary row.type that owns it.',
    generatedFrom: 'REF-1.1-E0-manifest.json',
    count: sites.length,
    sites,
  };
}

const serialize = (o) => JSON.stringify(o, null, 2) + '\n';

if (import.meta.url === `file://${process.argv[1]}`) {
  const fresh = generate();
  if (process.argv.includes('--write')) {
    writeFileSync(OUT, serialize(fresh));
    console.log(`wrote ${OUT} (${fresh.count} sites)`);
  } else {
    let committed = null;
    try { committed = readFileSync(OUT, 'utf8'); } catch { /* not yet written */ }
    const inSync = committed === serialize(fresh);
    console.log(serialize(fresh));
    console.log(inSync ? 'IN SYNC with committed artifact' : 'OUT OF SYNC — run with --write');
    process.exit(inSync ? 0 : 1);
  }
}
