/**
 * region-names.js — canonical human-readable names for all 192 Axona regions.
 *
 * Each 8-bit S2 region code (utils/s2.js — codes [0,192)) is made of TWO S2
 * level-3 sub-cells: the cell's two "halves". Axona names each half so a user
 * sees the name closest to their actual location, while BOTH names resolve to
 * the same region code. Where a cell is one homogeneous place (a single
 * country, open ocean) the two names are identical.
 *
 * REGION_NAMES[code] = [nameHalf0, nameHalf1], matching geoCellHalf(lat,lng)
 * (0 = lower Hilbert sub-cell). Generated by scripts/gen-region-names.mjs from
 * each sub-cell's geographic center and frozen here as the canonical list.
 *
 * Conventions (enforced by test/smoke_region_names.js):
 *   • names match /^[a-z0-9_]{1,13}$/  (lowercase, no spaces)
 *   • full names where they fit (colombia, scandinavia, kazakhstan)
 *   • open ocean → "<oce3>_<hex>"  (pac_68, atl_0a, ind_22, sou_a3, arc_44)
 *   • a small island names only ONE cell (claim-once); large landmasses span
 *     cells with a COMPASS suffix (japanse, kamchatkas) — never a number
 *   • last-resort land tiebreak is "_<hex>"
 *   • every name maps to exactly one code (name → code is well-defined)
 */

import { geoCellId, geoCellHalf, isValidCellId, S2_CELL_COUNT } from './s2.js';

/** [half0, half1] region names for every code, indexed by code [0,192). */
export const REGION_NAMES = Object.freeze([
  ['atl_00', 'saopauloe'], ['atl_01', 'atl_01'], ['atl_02', 'atl_02'],
  ['atl_03', 'atl_03'], ['atl_04', 'sthelena'], ['atl_05', 'ascension'],
  ['atl_06', 'atl_06'], ['brazil', 'brazil'], ['atl_08', 'atl_08'],
  ['capeverde', 'atl_09'], ['atl_0a', 'atl_0a'], ['azores', 'atl_0b'],
  ['canary', 'iberiaw'], ['iberia', 'morocco'], ['mali', 'atl_0e'],
  ['atl_0f', 'westafrica'], ['nigeria', 'congonw'], ['chad', 'niger'],
  ['algeria', 'italysw'], ['italy', 'libya'], ['egypt', 'turkey'],
  ['levant', 'arabia'], ['ethiopia', 'sudan'], ['congone', 'ethiopias'],
  ['eastafrica', 'tanzaniase'], ['ind_19', 'tanzania'], ['congo', 'atl_1a'],
  ['atl_1b', 'angola'], ['namibia', 'atl_1c'], ['atl_1d', 'atl_1d'],
  ['southafrica', 'southafrica'], ['ind_1f', 'ind_1f'], ['ind_20', 'madagascar'],
  ['ind_21', 'ind_21'], ['ind_22', 'ind_22'], ['ind_23', 'ind_23'],
  ['ind_24', 'ind_24'], ['ind_25', 'ind_25'], ['ind_26', 'mauritius'],
  ['ind_27', 'seychelles'], ['somalia', 'ind_28'], ['ind_29', 'somaliane'],
  ['arabiae', 'iran'], ['iranne', 'pakistansw'], ['pakistan', 'pakistan'],
  ['tibet', 'tibet'], ['southindia', 'southindia'], ['maldives', 'srilanka'],
  ['sumatra', 'sumatra'], ['vietnam', 'myanmar'], ['bengal', 'chinanw'],
  ['china', 'southchina'], ['taiwan', 'koreaw'], ['korea', 'pac_35'],
  ['philippines', 'philippines'], ['borneo', 'pac_37'], ['pac_38', 'oznorth'],
  ['pac_39', 'indonesia'], ['malaysia', 'ind_3a'], ['ind_3b', 'ind_3b'],
  ['ind_3c', 'ind_3c'], ['ind_3d', 'ind_3d'], ['pac_3e', 'ozwest'],
  ['ozcentral', 'ozcentral'], ['caucasus', 'ukraine'], ['russia', 'kazakhstansw'],
  ['kazakhstan', 'pac_42'], ['siberiaw', 'urals'], ['arc_44', 'arc_44'],
  ['svalbard', 'svalbard'], ['scandinavia', 'baltic'], ['poland', 'europe'],
  ['uk', 'faroe'], ['atl_49', 'atl_49'], ['atl_4a', 'atl_4a'],
  ['atl_4b', 'atl_4b'], ['quebec', 'quebec'], ['quebecsw', 'pac_4d'],
  ['greenland', 'greenland'], ['iceland', 'arctic'], ['arc_50', 'arc_50'],
  ['alaskane', 'arc_51'], ['canada', 'canada'], ['canadasw', 'pac_53'],
  ['pac_54', 'uswestnw'], ['pac_55', 'pac_55'], ['pac_56', 'alaska'],
  ['pac_57', 'pac_57'], ['pac_58', 'kamchatkas'], ['kamchatka', 'kamchatka'],
  ['arc_5a', 'arc_5a'], ['arc_5b', 'eastsib'], ['eastsibsw', 'siberia'],
  ['mongolia', 'mongolia'], ['koreanw', 'pac_5e'], ['pac_5f', 'japan'],
  ['japanse', 'pac_60'], ['pac_61', 'pac_61'], ['guam', 'pac_62'],
  ['pac_63', 'pac_63'], ['pac_64', 'marshall'], ['pac_65', 'pac_65'],
  ['pac_66', 'pac_66'], ['pac_67', 'pac_67'], ['pac_68', 'pac_68'],
  ['pac_69', 'pac_69'], ['pac_6a', 'pac_6a'], ['pac_6b', 'hawaii'],
  ['pac_6c', 'pac_6c'], ['pac_6d', 'kiribati'], ['pac_6e', 'pac_6e'],
  ['pac_6f', 'pac_6f'], ['pac_70', 'samoa'], ['pac_71', 'pac_71'],
  ['pac_72', 'pac_72'], ['pac_73', 'tahiti'], ['pac_74', 'pac_74'],
  ['pac_75', 'pac_75'], ['pac_76', 'pac_76'], ['tonga', 'pac_77'],
  ['nzealand', 'nzealand'], ['pac_79', 'pac_79'], ['fiji', 'pac_7a'],
  ['solomon', 'newcaled'], ['pac_7c', 'pac_7c'], ['png', 'png'],
  ['ozcentralne', 'ozeastne'], ['ozeast', 'ozeast'], ['pac_80', 'uswest'],
  ['pac_81', 'pac_81'], ['pac_82', 'pac_82'], ['pac_83', 'pac_83'],
  ['mexicosw', 'pac_84'], ['galapagos', 'guatemala'], ['mexico', 'mexico'],
  ['ussw', 'uscentral'], ['useastw', 'usse'], ['bahamas', 'useast'],
  ['bermuda', 'atl_8a'], ['atl_8b', 'atl_8b'], ['venezuelane', 'atl_8c'],
  ['atl_8d', 'venezuela'], ['colombia', 'caribbean'], ['cuba', 'pac_8f'],
  ['pac_90', 'pac_90'], ['peru', 'peru'], ['amazon', 'brazilnw'],
  ['brazilsw', 'bolivia'], ['argentinane', 'saopaulo'], ['atl_95', 'argentina'],
  ['chile', 'chile'], ['pac_97', 'pac_97'], ['pac_98', 'pac_98'],
  ['easter', 'pac_99'], ['pac_9a', 'pac_9a'], ['pac_9b', 'pac_9b'],
  ['pac_9c', 'pac_9c'], ['pac_9d', 'pac_9d'], ['pac_9e', 'pac_9e'],
  ['pac_9f', 'pac_9f'], ['pac_a0', 'pac_a0'], ['pac_a1', 'pac_a1'],
  ['pac_a2', 'pac_a2'], ['sou_a3', 'sou_a3'], ['sou_a4', 'sou_a4'],
  ['rossante', 'sou_a5'], ['sou_a6', 'sou_a6'], ['pac_a7', 'pac_a7'],
  ['pac_a8', 'sou_a8'], ['falklands', 'patagonia'], ['patagoniae', 'atl_aa'],
  ['atl_ab', 'atl_ab'], ['sou_ac', 'atl_ac'], ['atl_ad', 'sou_ad'],
  ['sou_ae', 'antpenine'], ['antpenin', 'antarctica'], ['antarcticae', 'eastant'],
  ['sou_b1', 'sou_b1'], ['sou_b2', 'atl_b2'], ['atl_b3', 'sou_b3'],
  ['ind_b4', 'ind_b4'], ['ind_b5', 'ind_b5'], ['kerguelen', 'sou_b6'],
  ['sou_b7', 'ind_b7'], ['ind_b8', 'ind_b8'], ['sou_b9', 'sou_b9'],
  ['eastante', 'rossant'], ['rossantnw', 'sou_bb'], ['sou_bc', 'sou_bc'],
  ['pac_bd', 'pac_bd'], ['pac_be', 'pac_be'], ['pac_bf', 'pac_bf'],
].map(Object.freeze));

/** name (lowercase) → code. Built once; both half-names map to their code. */
const NAME_TO_CODE = (() => {
  const m = new Map();
  REGION_NAMES.forEach((pair, code) => {
    for (const name of pair) if (!m.has(name)) m.set(name, code);
  });
  return m;
})();

/**
 * Both region names for a code (the two halves).
 * @param {number} code  integer in [0,192)
 * @returns {[string,string]|null}
 */
export function regionNames(code) {
  return isValidCellId(code) ? REGION_NAMES[code] : null;
}

/**
 * A region name for a code. With a coordinate, returns the name for the half
 * the point is in (closest to the user's location); otherwise the first half.
 * @param {number} code
 * @param {number} [lat]
 * @param {number} [lng]
 * @returns {string|null}
 */
export function regionName(code, lat, lng) {
  if (!isValidCellId(code)) return null;
  const half = (typeof lat === 'number' && typeof lng === 'number') ? geoCellHalf(lat, lng) : 0;
  return REGION_NAMES[code][half];
}

/**
 * Region code for a region name (case-insensitive). Either half-name works.
 * @param {string} name
 * @returns {number|null}
 */
export function regionCode(name) {
  if (typeof name !== 'string') return null;
  const code = NAME_TO_CODE.get(name.trim().toLowerCase());
  return code === undefined ? null : code;
}

/**
 * Resolve a region token — a NAME (either half) or a numeric code — to its
 * 8-bit code. Accepts 'useast', 'USEAST', '0x89', '137', or 137.
 * @param {string|number} token
 * @returns {number|null}
 */
export function resolveRegion(token) {
  if (typeof token === 'number') return isValidCellId(token) ? token : null;
  if (typeof token !== 'string') return null;
  const t = token.trim();
  const byName = regionCode(t);
  if (byName !== null) return byName;
  const n = /^0x[0-9a-f]+$/i.test(t) ? parseInt(t, 16)
          : /^\d+$/.test(t)          ? parseInt(t, 10)
          : NaN;
  return isValidCellId(n) ? n : null;
}

/**
 * The location-appropriate region name for a (lat,lng): the name of the half
 * the coordinate falls in.
 * @param {number} lat
 * @param {number} lng
 * @returns {string}
 */
export function regionNameForLatLng(lat, lng) {
  const code = geoCellId(lat, lng, 8);
  return REGION_NAMES[code][geoCellHalf(lat, lng)];
}

if (REGION_NAMES.length !== S2_CELL_COUNT) {
  throw new Error(
    `region-names.js: have ${REGION_NAMES.length} regions, expected ${S2_CELL_COUNT}`);
}
