/**
 * region-names.js — canonical human-readable names for all 192 Axona regions.
 *
 * Each 8-bit S2 region code (utils/s2.js — codes [0,192)) is made of TWO S2
 * level-3 sub-cells: the cell's two "halves". Axona names each half so a user
 * sees the name closest to their actual location, while BOTH names resolve to
 * the same region code. Where a cell is one homogeneous place (a single country,
 * open ocean) the two names are identical.
 *
 * REGION_NAMES[code] = [nameHalf0, nameHalf1], matching geoCellHalf(lat,lng)
 * (0 = lower Hilbert sub-cell). Generated by scripts/gen-region-names.mjs from
 * each sub-cell's geographic center and frozen here as the canonical list.
 *
 * Naming rules (enforced by test/smoke_region_names.js):
 *   • names match /^[a-z0-9_]{1,13}$/  (lowercase, no spaces)
 *   • full names where they fit (colombia, europe, uk, scandinavia, blacksea)
 *   • open ocean (no land/island near a half) → "<oce3>_<hex>"  (pac_68, atl_0a,
 *     ind_22, sou_a3, arc_51) — first 3 letters of the basin + the region code
 *   • an island in a half uses the island name (hawaii, fiji, azores, …)
 *   • a base repeated across cells is disambiguated by COMPASS, never a number;
 *     last-resort tiebreak is "_<hex>"
 *   • every name maps to exactly one code (name → code is well-defined)
 */

import { geoCellId, geoCellHalf, isValidCellId, S2_CELL_COUNT } from './s2.js';

/** [half0, half1] region names for every code, indexed by code [0,192). */
export const REGION_NAMES = Object.freeze([
  ['saopaulose', 'saopaulose'], ['atl_01', 'atl_01'], ['atl_02', 'atl_02'],
  ['sthelenas', 'atl_03'], ['sthelena', 'sthelena'], ['sthelenan', 'atl_05'],
  ['atl_06', 'atl_06'], ['brazil', 'brazil'], ['atl_08', 'capeverdesw'],
  ['capeverde', 'atl_09'], ['atl_0a', 'azoressw'], ['azores', 'capeverdenw'],
  ['canary', 'azorese'], ['iberia', 'canarye'], ['westafricanw', 'capeverdee'],
  ['atl_0f', 'westafrica'], ['westafricase', 'congonw'], ['sahel', 'sahel'],
  ['saharanw', 'italysw'], ['italy', 'sahara'], ['egypt', 'greece'],
  ['levant', 'arabia'], ['ethiopian', 'egypts'], ['congone', 'ethiopia'],
  ['eastafrica', 'madagascarnw'], ['angolase', 'congose'], ['congo', 'atl_1a'],
  ['sthelenae', 'angola'], ['southafricaw', 'atl_1c'], ['atl_1d', 'southafricasw'],
  ['southafrica', 'southafrica'], ['madagascarsw', 'ind_1f'], ['ind_20', 'madagascar'],
  ['mauritiusse', 'ind_21'], ['kerguelenne', 'ind_22'], ['ind_23', 'ind_23'],
  ['ind_24', 'ind_24'], ['srilankase', 'maldivess'], ['seychellese', 'mauritius'],
  ['madagascarne', 'seychelles'], ['somalia', 'seychellesne'], ['ind_29', 'somaliane'],
  ['arabiae', 'iran'], ['iranne', 'pakistansw'], ['pakistan', 'pakistan'],
  ['tibet', 'tibet'], ['southindia', 'southindia'], ['maldives', 'srilanka'],
  ['malaysia', 'malaysia'], ['vietnam', 'thailand'], ['bengal', 'chinanw'],
  ['china', 'southchina'], ['taiwan', 'koreaw'], ['korea', 'taiwane'],
  ['philippines', 'philippines'], ['borneo', 'philippinesse'], ['oznorth', 'oznorth'],
  ['ozwestn', 'indonesia'], ['malaysias', 'malaysias'], ['ind_3b', 'ind_3b'],
  ['ozwestw', 'ind_3c'], ['ind_3d', 'ind_3d'], ['ozwest', 'ozwest'],
  ['ozcentral', 'ozcentral'], ['caucasus', 'ukraine'], ['russia', 'caucasusne'],
  ['uralsse', 'siberiasw'], ['siberia', 'urals'], ['uralsnw', 'siberianw'],
  ['arctic', 'svalbard'], ['scandinavia', 'baltic'], ['balkans', 'europe'],
  ['uk', 'faroe'], ['iceland', 'azoresne'], ['azoresnw', 'atl_4a'],
  ['quebecse', 'atl_4b'], ['quebec', 'quebec'], ['quebecnw', 'quebecnw'],
  ['greenland', 'greenland'], ['greenlande', 'arcticsw'], ['arctic_50', 'alaskanw'],
  ['alaskane', 'arc_51'], ['canada', 'canada'], ['canadasw', 'canadasw'],
  ['pac_54', 'uswestnw'], ['uswest_55', 'pac_55'], ['pac_56', 'alaska'],
  ['alaskasw', 'pac_57'], ['kamchatkase', 'kamchatkase'], ['kamchatka', 'kamchatka'],
  ['arc_5a', 'arcticse'], ['eastsib', 'eastsib'], ['eastsibsw', 'siberiae'],
  ['mongolia', 'mongolia'], ['koreanw', 'pac_5e'], ['japanne', 'japanne'],
  ['japan', 'japan'], ['pac_61', 'guamnw'], ['guam', 'guam'],
  ['guamse', 'guamse'], ['marshall', 'marshall'], ['marshalle', 'marshalle'],
  ['pac_66', 'pac_66'], ['pac_67', 'pac_67'], ['pac_68', 'pac_68'],
  ['hawaiinw', 'pac_69'], ['pac_6a', 'pac_6a'], ['pac_6b', 'hawaii'],
  ['hawaiise', 'pac_6c'], ['pac_6d', 'kiribati'], ['kiribatinw', 'hawaiisw'],
  ['pac_6f', 'pac_6f'], ['samoa', 'samoa'], ['samoae', 'kiribatisw'],
  ['kiribatise', 'pac_72'], ['tahiti', 'tahiti'], ['tahitise', 'tahitise'],
  ['pac_75', 'pac_75'], ['pac_76', 'tongase'], ['tonga', 'nzealandne'],
  ['nzealand', 'nzealand'], ['newcaledse', 'newcaledse'], ['fiji', 'fiji'],
  ['solomon', 'newcaled'], ['solomonsw', 'pnge'], ['png', 'oznorthe'],
  ['ozcentralne', 'ozeastne'], ['ozeast', 'ozeast'], ['uswest', 'uswest'],
  ['uswestse', 'pac_81'], ['pac_82', 'pac_82'], ['pac_83', 'pac_83'],
  ['mexicosw', 'pac_84'], ['galapagos', 'guatemala'], ['mexico', 'mexico'],
  ['uscentral', 'uscentral'], ['useastw', 'bahamasnw'], ['bahamas', 'useast'],
  ['bermudane', 'bermudane'], ['atl_8b', 'bermuda'], ['venezuelane', 'atl_8c'],
  ['atl_8d', 'venezuela'], ['colombia', 'caribbean'], ['guatemalae', 'galapagosne'],
  ['galapagosse', 'perusw'], ['peru', 'peru'], ['amazon', 'brazilnw'],
  ['brazilsw', 'amazons'], ['argentinane', 'saopaulo'], ['saopaulosw', 'argentina'],
  ['chile', 'chile'], ['chilenw', 'patagonianw'], ['pac_98', 'easterse'],
  ['easter', 'easter'], ['pac_9a', 'galapagossw'], ['pac_9b', 'easterne'],
  ['pac_9c', 'pac_9c'], ['pac_9d', 'pac_9d'], ['pac_9e', 'easterw'],
  ['eastersw', 'pac_9f'], ['pac_a0', 'pac_a0'], ['pac_a1', 'pac_a1'],
  ['pac_a2', 'nzealandse'], ['sou_a3', 'sou_a3'], ['sou_a4', 'rossantne'],
  ['rossante', 'sou_a5'], ['sou_a6', 'sou_a6'], ['pac_a7', 'pac_a7'],
  ['patagoniasw', 'antpeninnw'], ['falklands', 'patagonia'], ['falklandsne', 'atl_aa'],
  ['atl_ab', 'falklandse'], ['sou_ac', 'atl_ac'], ['atl_ad', 'sou_ad'],
  ['antarcticanw', 'antpenine'], ['antpenin', 'antarctica'], ['antarcticane', 'eastant'],
  ['sou_b1', 'antarctica_b1'], ['sou_b2', 'atl_b2'], ['atl_b3', 'sou_b3'],
  ['ind_b4', 'ind_b4'], ['ind_b5', 'kerguelennw'], ['kerguelen', 'kerguelen'],
  ['sou_b7', 'kerguelene'], ['ind_b8', 'ind_b8'], ['sou_b9', 'sou_b9'],
  ['eastante', 'rossant'], ['rossantnw', 'sou_bb'], ['sou_bc', 'sou_bc'],
  ['nzealandsw', 'nzealandsw'], ['pac_be', 'pac_be'], ['pac_bf', 'pac_bf'],
].map(Object.freeze));

/** name (lowercase) → code. Built once; both half-names map to their code. */
const NAME_TO_CODE = (() => {
  const m = new Map();
  REGION_NAMES.forEach((pair, code) => {
    for (const name of pair) if (!m.has(name)) m.set(name, code);
  });
  return m;
})();

/**
 * Both region names for a code (the two halves).
 * @param {number} code  integer in [0,192)
 * @returns {[string,string]|null}
 */
export function regionNames(code) {
  return isValidCellId(code) ? REGION_NAMES[code] : null;
}

/**
 * A region name for a code. With a coordinate, returns the name for the half
 * the point is in (closest to the user's location); otherwise the first half.
 * @param {number} code
 * @param {number} [lat]
 * @param {number} [lng]
 * @returns {string|null}
 */
export function regionName(code, lat, lng) {
  if (!isValidCellId(code)) return null;
  const half = (typeof lat === 'number' && typeof lng === 'number') ? geoCellHalf(lat, lng) : 0;
  return REGION_NAMES[code][half];
}

/**
 * Region code for a region name (case-insensitive). Either half-name works.
 * @param {string} name
 * @returns {number|null}
 */
export function regionCode(name) {
  if (typeof name !== 'string') return null;
  const code = NAME_TO_CODE.get(name.trim().toLowerCase());
  return code === undefined ? null : code;
}

/**
 * Resolve a region token — a NAME (either half) or a numeric code — to its
 * 8-bit code. Accepts 'useast', 'USEAST', '0x89', '137', or 137.
 * @param {string|number} token
 * @returns {number|null}
 */
export function resolveRegion(token) {
  if (typeof token === 'number') return isValidCellId(token) ? token : null;
  if (typeof token !== 'string') return null;
  const t = token.trim();
  const byName = regionCode(t);
  if (byName !== null) return byName;
  const n = /^0x[0-9a-f]+$/i.test(t) ? parseInt(t, 16)
          : /^\d+$/.test(t)          ? parseInt(t, 10)
          : NaN;
  return isValidCellId(n) ? n : null;
}

/**
 * The location-appropriate region name for a (lat,lng): the name of the half
 * the coordinate falls in.
 * @param {number} lat
 * @param {number} lng
 * @returns {string}
 */
export function regionNameForLatLng(lat, lng) {
  const code = geoCellId(lat, lng, 8);
  return REGION_NAMES[code][geoCellHalf(lat, lng)];
}

if (REGION_NAMES.length !== S2_CELL_COUNT) {
  throw new Error(
    `region-names.js: have ${REGION_NAMES.length} regions, expected ${S2_CELL_COUNT}`);
}
